#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:30:00

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH --time=01:30:00

set -x
set -e



singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py

