#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:30:00

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=20G
#SBATCH --time=01:30:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_figs
mkdir -p out_report



singularity exec docker://aunnikri642/app-freesurfer-mne-source-recon python3 main.py

